import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../core/pdf_text.dart';
import 'crucible_feature.dart';

/// Builds a shareable PDF from a Crucible session — the idea, the full
/// Zetra transcript, dossier findings, and the Arbiter's report — and
/// hands it to the native share sheet.
class ExportService {
  static Future<void> exportAndShare(CrucibleController controller) async {
    final version = controller.currentVersion;
    if (version == null) return;

    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('CRUCIBLE',
                style: pw.TextStyle(fontSize: 10, letterSpacing: 3, color: PdfColors.grey600)),
            pw.SizedBox(height: 4),
            pw.Text(pdfSafe(controller.title), style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
            pw.Text(pdfSafe(controller.oneLiner),
                style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700, fontStyle: pw.FontStyle.italic)),
            pw.SizedBox(height: 4),
            pw.Divider(),
          ],
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Crucible - v${version.versionNumber} - Stage ${controller.stageIndex}/${controller.totalStages}',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
            ),
            pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          ],
        ),
        build: (context) => [
          _sectionTitle('THE IDEA'),
          pw.Text(pdfSafe(version.content), style: const pw.TextStyle(fontSize: 10, lineSpacing: 3)),
          pw.SizedBox(height: 16),
          _sectionTitle('PRESSURE TEST TRANSCRIPT'),
          ...controller.messages.where((m) => !m.isReport).map(
                (m) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 8),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        pdfSafe(m.fromZetra
                            ? 'ZETRA${m.stageLabel != null ? " - ${m.stageLabel}" : ""}${m.isHold ? " (HELD)" : ""}'
                            : 'INNOVATOR'),
                        style: pw.TextStyle(
                          fontSize: 8,
                          fontWeight: pw.FontWeight.bold,
                          color: m.fromZetra
                              ? (m.isHold ? PdfColors.orange800 : PdfColors.red800)
                              : PdfColors.blue800,
                        ),
                      ),
                      pw.SizedBox(height: 2),
                      pw.Text(pdfSafe(m.text), style: const pw.TextStyle(fontSize: 10)),
                    ],
                  ),
                ),
              ),
          pw.SizedBox(height: 16),
          if (controller.findings.isNotEmpty) ...[
            _sectionTitle('DOSSIER - FINDINGS'),
            ...controller.findings.map(
              (f) => pw.Bullet(text: pdfSafe('[${f.tag.name}] ${f.text}'), style: const pw.TextStyle(fontSize: 10)),
            ),
            pw.SizedBox(height: 16),
          ],
          if (controller.report != null) ...[
            _sectionTitle('ARBITER REPORT'),
            _reportBlock('Strongest Arguments', controller.report!.strongestArguments),
            _reportBlock('Weakest Arguments', controller.report!.weakestArguments),
            _reportBlock('Unsupported Assumptions', controller.report!.unsupportedAssumptions),
            _reportBlock('Contradictions', controller.report!.contradictions),
            _reportBlock('Unanswered Questions', controller.report!.unansweredQuestions),
            _reportBlock('Suggested Experiments', controller.report!.suggestedExperiments),
            if (controller.report!.readinessSummary.isNotEmpty) ...[
              pw.SizedBox(height: 8),
              pw.Text('Readiness Summary', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
              pw.Text(pdfSafe(controller.report!.readinessSummary),
                  style: pw.TextStyle(fontSize: 10, fontStyle: pw.FontStyle.italic)),
            ],
          ] else ...[
            _sectionTitle('ARBITER REPORT'),
            pw.Text('No judgment requested yet.',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic)),
          ],
        ],
      ),
    );

    final bytes = await doc.save();
    final safeTitle = controller.title.replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_');
    await Printing.sharePdf(bytes: bytes, filename: 'crucible_$safeTitle.pdf');
  }

  static pw.Widget _sectionTitle(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Text(text, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, letterSpacing: 1)),
      );

  static pw.Widget _reportBlock(String title, List<String> items) {
    if (items.isEmpty) return pw.SizedBox();
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          ...items.map((i) => pw.Bullet(text: pdfSafe(i), style: const pw.TextStyle(fontSize: 10))),
        ],
      ),
    );
  }
}
